openapi: "3.0.0"
info:
  title: "Clients API"
  version: "3.0"
  contact:
    name: "Land"
    email: "ISGLand@JohnDeere.com"
servers:
  - url: "https://{environment}.deere.com/platform"
    variables:
      environment:
        default: "api"
        enum:
          - "api"
          - "apicert"
          - "apiqa.tal"
          - "sandboxapi"
          - "partnerapi"
paths:
  /organizations/{orgId}/clients:
    get:
      description: "Retrieve all of the clients for an organization"
      summary: "List Clients in an Org"
      operationId: "getAllClients"
      parameters:
        - $ref: "#/components/parameters/OrgId"
        - $ref: "#/components/parameters/Embed"
        - $ref: "#/components/parameters/RecordFilter"
      responses:
        "200":
          $ref: "#/components/responses/ClientsReturned"
        "304":
          $ref: "#/components/responses/HasNotChanged"
        "403":
          $ref: "#/components/responses/DoesNotHaveAccessResponse"
        "404":
          $ref: "#/components/responses/OrgNotFound"
    post:
      description: "This API is used to create a new client resource within the target organization. In order to do this, the authenticated user must have Locations Level 3 permission within the target organization. Note: All clients are created with an \"active\" status."
      summary: "Create a Client"
      operationId: "createClient"
      security:
        - OAuth2:
            - "ag3"
      parameters:
        - $ref: "#/components/parameters/OrgId2"
      requestBody:
        $ref: "#/components/requestBodies/ClientRequest"
      responses:
        "200":
          $ref: "#/components/responses/ClientCreatedResponse"
        "400":
          $ref: "#/components/responses/MalformedRequest"
        "403":
          $ref: "#/components/responses/DoesNotHaveAccessResponse"
        "404":
          $ref: "#/components/responses/OrgOrClientNotFound"
  /organizations/{orgId}/clients/{clientId}:
    parameters:
      - $ref: "#/components/parameters/OrgId"
      - $ref: "#/components/parameters/ClientId"
    get:
      description: "View a clients details. For each client, the response will link to the following resources: fields: View the field the client belongs to. farms: View the farm belonging to the client. owningOrganization: View the org that owns the client."
      summary: "View a Client"
      operationId: "getClient"
      parameters:
        - $ref: "#/components/parameters/Embed"
      responses:
        "200":
          $ref: "#/components/responses/ClientReturned"
        "403":
          $ref: "#/components/responses/DoesNotHaveAccessResponse"
        "404":
          $ref: "#/components/responses/OrgOrClientNotFound"
    put:
      description: "This API is used to update an existing client resource within the target organization. In order to do this, the authenticated user must have Locations Level 3 permission within the target organization."
      summary: "Update a Client"
      operationId: "updateClient"
      requestBody:
        $ref: "#/components/requestBodies/ClientRequest2"
      responses:
        "204":
          $ref: "#/components/responses/UpdatedResponse"
        "400":
          $ref: "#/components/responses/MalformedRequest"
        "403":
          $ref: "#/components/responses/DoesNotHaveAccessResponse"
        "404":
          $ref: "#/components/responses/OrgOrClientNotFound"
    delete:
      description: "This API is used to delete a client resource within the target organization. In order to do this, the authenticated user must have Locations Level 3 permission within the target organization."
      summary: "Delete a Client"
      operationId: "deleteClient"
      responses:
        "204":
          $ref: "#/components/responses/DeletedResponse"
        "403":
          $ref: "#/components/responses/DoesNotHaveAccessResponse"
        "404":
          $ref: "#/components/responses/OrgOrClientNotFound"
  /organizations/{orgId}/clients/{id}/farms:
    parameters:
      - $ref: "#/components/parameters/OrgId"
      - $ref: "#/components/parameters/ClientId"
      - $ref: "#/components/parameters/FarmName"
    get:
      description: "View a list of farms belonging to a specified client. For each farm, the response will link to the following resources: fields: View the fields in this farm farms: View the clients that own this farm. owningOrganization: View the Organization that owns the farm."
      summary: "View a Client's Farms"
      operationId: "getAllFarms"
      responses:
        "200":
          $ref: "#/components/responses/FarmsResponse"
        "304":
          $ref: "#/components/responses/HasNotChanged"
        "403":
          $ref: "#/components/responses/DoesNotHaveAccessResponse"
        "404":
          $ref: "#/components/responses/OrgNotFound"
  /organizations/{orgID}/clients/{id}/fields:
    get:
      description: "View the field to which a specific client belongs. For the client, the response links to the following resources: boundaries: View the boundaries that belong to this field. clients: View the client that belongs to this field. farms: View the farms within this field. owningOrganization: View the organization that owns the field."
      summary: "View a Client's Field"
      security:
        - OAuth2:
            - "ag1"
      parameters:
        - $ref: "#/components/parameters/OrgId"
        - $ref: "#/components/parameters/Id"
        - $ref: "#/components/parameters/X-deere-signature"
      responses:
        "200":
          description: "Get Field by client Id"
          content:
            application/vnd.deere.axiom.v3+json:
              schema:
                properties:
                  links:
                    type: "array"
                    items:
                      $ref: "#/components/schemas/GroupLinkID"
                  total:
                    type: "integer"
                    example: 1
                    format: "int32"
                  values:
                    type: "array"
                    items:
                      $ref: "#/components/schemas/FieldResponse"
              examples:
                No Header:
                  description: "20O OK Content-Type: application/vnd.deere.axiom.v3+jsonx-deere-signature: 3b5392615e4b4e1c92013026f47109bb"
                  value:
                    links:
                      - rel: "self"
                        uri: "https://sandboxapi.deere.com/platform/organizations/1234/clients/f1161eba-7c82-4a80-9eeb-383451b4c46e/fields"
                    total: 1
                    values:
                      - name: "Narnia"
                        archived: false
                        id: "a7cb723f-6707-46fb-a9ff-4e734e3daf58"
                        links:
                          - rel: "self"
                            uri: "https://sandboxapi.deere.com/platform/organizations/1234/fields/a7cb723f-6707-46fb-a9ff-4e734e3daf58"
                          - rel: "boundaries"
                            uri: "https://sandboxapi.deere.com/platform/organizations/1234/fields/a7cb723f-6707-46fb-a9ff-4e734e3daf58/boundaries"
                          - rel: "clients"
                            uri: "https://sandboxapi.deere.comm/platform/organizations/1234/fields/a7cb723f-6707-46fb-a9ff-4e734e3daf58/clients"
                          - rel: "farms"
                            uri: "https://sandboxapi.deere.com/platform/organizations/1234/fields/a7cb723f-6707-46fb-a9ff-4e734e3daf58/farms"
                          - rel: "owningOrganization"
                            uri: "https://sandboxapi.deere.com/platform/organizations/1234"
                          - rel: "contributionDefinition"
                            uri: "https://sandboxapi.deere.com/platform/contributionDefinitions/32a256ea-0000-4756-b000-b6dabda856ef"
components:
  parameters:
    OrgId:
      in: "path"
      name: "orgId"
      description: "The id of the organization"
      x-required-boolean: true
      schema:
        type: "integer"
        format: "int64"
        example: 12345
    ClientId:
      in: "path"
      name: "clientId"
      description: "client Id"
      x-required-boolean: true
      schema:
        type: "string"
        example: "9369f3f6-2428-4bba-bf64-0a19cdaf007d"
    ClientName:
      in: "query"
      name: "name"
      description: "client name"
      x-required-boolean: false
      schema:
        type: "string"
    FarmName:
      in: "query"
      name: "name"
      description: "farm name"
      x-required-boolean: false
      schema:
        type: "string"
    RecordFilter:
      in: "query"
      name: "recordFilter"
      description: "Filter clients by status. Possible values ACTIVE or ALL or ARCHIVED Default - ACTIVE"
      schema:
        type: "string"
        example: "ACTIVE"
    Embed:
      name: "embed"
      in: "query"
      description: "Populates response with data lineage information"
      x-required-boolean: false
      schema:
        type: "string"
        example: "showRecordMetadata"
    X-deere-signature:
      name: "x-deere-signature"
      in: "header"
      description: "x-deere-signature should be managed by the client per user per API. For a new user/new API, the first request will have a blank value for x-deere-signature. Changes can be tracked with the x-deere-signature returned in the response. If the response has not changed since the last API call, the value of x-deere-signature is not changed and the client should use the same String Token next time."
      schema:
        type: "string"
        example: "9r8392615e4b4e1c92018026f47109bb"
    OrgId2:
      in: "path"
      name: "orgID"
      description: "The ID of the organization"
      x-required-boolean: true
      schema:
        type: "string"
        format: "int64"
        example: 123456
    Id:
      name: "clientId"
      in: "path"
      description: "Client ID"
      x-required-boolean: true
      schema:
        type: "string"
        format: "uuid"
        example: "f1161eba-7c82-4a80-9eeb-383451b4c46e"
  requestBodies:
    ClientRequest:
      description: "The request body used to create or update a client"
      content:
        application/vnd.deere.axiom.v3+json:
          schema:
            $ref: "#/components/schemas/ClientPost"
          examples:
            Create new client:
              value:
                name: "UniqueClientName"
                archived: false
    ClientRequest2:
      description: "The request body used to create or update a client"
      content:
        application/vnd.deere.axiom.v3+json:
          schema:
            properties:
              name:
                example: "UniqueClientName"
                type: "string"
                description: "New Client Name"
              archived:
                type: "string"
                example: "false"
                description: "Archived status (false = active)"
          examples:
            Update client:
              value:
                name: "UniqueClientName"
                archived: true
  responses:
    ClientsReturned:
      description: "Array of clients containing links related to assets"
      content:
        application/vnd.deere.axiom.v3+json:
          schema:
            $ref: "#/components/schemas/Clients"
          examples:
            No Header:
              description: "200 OK Content-Type: application/vnd.deere.axiom.v3+json x-deere-signature: 5a5392615e4b4e1c92013026f47109bb"
              value:
                links:
                  - rel: "self"
                    uri: "https://sandboxapi.deere.com/platform/organizations/6789/clients"
                total: 2
                values:
                  - name: "Captain Nemo"
                    links:
                      - rel: "self"
                        uri: "https://sandboxapi.deere.com/platform/organizations/6789/clients/f1161eba-7c82-4a80-9eeb-383451b4c46e"
                      - rel: "fields"
                        uri: "https://sandboxapi.deere.com/platform/organizations/6789/clients/f1161eba-7c82-4a80-9eeb-383451b4c46e/fields"
                      - rel: "farms"
                        uri: "https://sandboxapi.deere.com/platform/organizations/6789/clients/f1161eba-7c82-4a80-9eeb-383451b4c46e/farms"
                      - rel: "owningOrganization"
                        uri: "https://sandboxapi.deere.com/platform/organizations/6789"
                    id: "f1161eba-7c82-4a80-9eeb-383451b4c46e"
                    archived: false
                  - name: "Aslan"
                    links:
                      - rel: "self"
                        uri: "https://sandboxapi.deere.com/platform/organizations/6789/clients/f1161eba-7c82-4a80-9eeb-383451b4c46e"
                      - rel: "fields"
                        uri: "https://sandboxapi.deere.com/platform/organizations/6789/clients/f1161eba-7c82-4a80-9eeb-383451b4c46e/fields"
                      - rel: "farms"
                        uri: "https://sandboxapi.deere.com/platform/organizations/6789/clients/f1161eba-7c82-4a80-9eeb-383451b4c46e/farms"
                      - rel: "owningOrganization"
                        uri: "https://sandboxapi.deere.com/platform/organizations/6789"
                    id: "f1161eba-7c82-4a80-9eeb-383451b4c46e"
                    archived: false
    ClientReturned:
      description: "Success"
      content:
        application/vnd.deere.axiom.v3+json:
          schema:
            $ref: "#/components/schemas/Client"
          examples:
            No Header:
              description: "200 OK Content-Type: application/vnd.deere.axiom.v3+json x-deere-signature: 5a5392615e4b4e1c92013026f47109bb"
              value:
                name: "Aslan"
                links:
                  - rel: "self"
                    uri: "https://sandboxapi.deere.com/platform/organizations/6789/clients/f1161eba-7c82-4a80-9eeb-383451b4c46e"
                  - rel: "fields"
                    uri: "https://sandboxapi.deere.com/platform/organizations/6789/clients/f1161eba-7c82-4a80-9eeb-383451b4c46e/fields"
                  - rel: "farms"
                    uri: "https://sandboxapi.deere.com/platform/organizations/6789/clients/f1161eba-7c82-4a80-9eeb-383451b4c46e/farms"
                  - rel: "owningOrganization"
                    uri: "https://sandboxapi.deere.com/platform/organizations/6789"
                id: "f1161eba-7c82-4a80-9eeb-383451b4c46e"
                archived: false
    ClientCreatedResponse:
      description: "created"
      headers:
        Location:
          schema:
            description: "The uri of the newly created resource"
            type: "string"
            format: "url"
            example: "https://sandboxapi.deere.com/platform/organizations/1234/clients/795b80cf-eb03-4c43-a9e1-f46eb0fbf912"
      content:
        application/vnd.deere.axiom.v3+json:
          schema:
            properties:
              total:
                type: "integer"
                example: 1
                format: "int32"
          examples:
            Headers:
              description: "201 Created Location: https://sandboxapi.deere.com/platform/organizations/12345/clients/4r539261-5e4b-4e1c-9201-8026f47109bb"
    FarmsResponse:
      description: "Get Farm by client Id"
      content:
        application/vnd.deere.axiom.v3+json:
          schema:
            properties:
              links:
                type: "array"
                items:
                  $ref: "#/components/schemas/GroupLink"
              total:
                type: "integer"
                example: 1
                format: "int32"
              values:
                type: "array"
                items:
                  $ref: "#/components/schemas/FarmResponse"
          examples:
            No Header:
              description: "200 OK Content-Type: application/vnd.deere.axiom.v3+json x-deere-signature: 5a5392615e4b4e1c92013026f47109bb"
              value:
                links:
                  - rel: "self"
                    uri: "https://sandboxapi.deere.com/platform/organizations/6789/clients/590f875c-9504-461e-94f3-b80a52372023/farms"
                total: 2
                values:
                  - name: "FarmName"
                    clientUri: "https://sandboxapi.deere.com/platform/organizations/592715/clients/e45d1773-cb82-468-96ac-ba65917dd274,"
                    archived: false
                    id: "f1161eba-7c82-4a80-9eeb-383451b4c46e"
                    links:
                      - rel: "self"
                        uri: "https://sandboxapi.deere.com/platform/organizations/6789/farms/f1161eba-7c82-4a80-9eeb-383451b4c46e"
                      - rel: "fields"
                        uri: "https://sandboxapi.deere.com/platform/organizations/6789/farms/f1161eba-7c82-4a80-9eeb-383451b4c46e/fields"
                      - rel: "farms"
                        uri: "https://sandboxapi.deere.com/platform/organizations/6789/farms/f1161eba-7c82-4a80-9eeb-383451b4c46e/clients"
                      - rel: "owningOrganization"
                        uri: "https://sandboxapi.deere.com/platform/organizations/6789"
    DeletedResponse:
      description: "Deleted"
      content:
        application/vnd.deere.axiom.v3+json:
          examples:
            Headers:
              description: "204 No Content"
    UpdatedResponse:
      description: "Updated"
      content:
        application/vnd.deere.axiom.v3+json:
          schema:
            properties:
              total:
                type: "integer"
                example: 1
                format: "int32"
          examples:
            Headers:
              description: "204 No Content"
    DoesNotHaveAccessResponse:
      description: "Does not have access"
    OrgNotFound:
      description: "Organization not found"
    HasNotChanged:
      description: "Content has not changed since last call"
    OrgOrClientNotFound:
      description: "Organization or client not found"
    MalformedRequest:
      description: "Request Validation failure."
      content:
        application/vnd.deere.axiom.v3+json:
          schema:
            $ref: "#/components/schemas/MalformedRequestError"
  schemas:
    Clients:
      type: "object"
      properties:
        links:
          type: "array"
          items:
            $ref: "#/components/schemas/GroupLink"
        total:
          type: "integer"
          example: 1
          format: "int32"
        values:
          type: "array"
          items:
            $ref: "#/components/schemas/Client"
    Client:
      type: "object"
      properties:
        "@type":
          type: "string"
          example: "Client"
          description: "Type"
        name:
          type: "string"
          example: "John Doe"
          description: "Client Name"
        id:
          type: "string"
          format: "uuid"
          example: "9369f3f6-2428-4bba-bf64-0a19cdaf007d"
          readOnly: true
          description: "Client ID"
        links:
          readOnly: true
          type: "array"
          items:
            $ref: "#/components/schemas/Link"
          description: "Links"
        archived:
          type: "boolean"
          example: true
          description: "Archived status"
    GroupLink:
      description: "Link to another resource"
      type: "object"
      required:
        - "rel"
        - "uri"
      properties:
        "@type":
          type: "string"
          example: "Link"
        rel:
          type: "string"
          example: "self"
        uri:
          type: "string"
          example: "https://sandboxapi.deere.com/platform/organizations/5555/clients"
    FieldResponse:
      properties:
        x-deere-signature:
          type: "string"
          description: "A new x-deere-signature response header will be included if the response has changed since last api call."
          example: "3b5392615e4b4e1c92013026f47109bb"
        id:
          type: "string"
          format: "uuid"
          example: "f1161eba-7c82-4a80-9eeb-383451b4c46e"
          description: "Client ID"
        name:
          type: "string"
          description: "Client Name"
          example: "Aslan"
    ContentType:
      properties: {}
    Link:
      description: "Link to another resource"
      type: "object"
      required:
        - "rel"
        - "uri"
      properties:
        "@type":
          type: "string"
          example: "Link"
        rel:
          type: "string"
          example: "self"
        uri:
          type: "string"
          example: "https://sandboxapi.deere.com/platform/organizations/5555/clients/9369f3f6-2428-4bba-bf64-0a19cdaf007d"
    GroupLinkID:
      properties:
        boundaries:
          example: "https://sandboxapi.deere.com/platform/organizations/1234/fields/a7cb723f-6707-46fb-a9ff-4e734e3daf58/boundaries"
          description: "Boundaries Link."
        clients:
          example: "https://sandboxapi.deere.com/platform/organizations/1234/fields/a7cb723f-6707-46fb-a9ff-4e734e3daf58/clients"
          description: "Clients Link."
        farms:
          example: "https://sandboxapi.deere.com/platform/organizations/1234/fields/a7cb723f-6707-46fb-a9ff-4e734e3daf58/farms"
          description: "Farms Link."
        owningOrganization:
          example: "https://sandboxapi.deere.com/platform/organizations/1234"
          description: "Organizations Link."
        contributionDefinition:
          example: "https://sandboxapi.deere.com/platform/contributionDefinitions/32a256ea-0000-4756-b000-b6dabda856ef"
          description: "Contribution Definition Link"
    ClientPost:
      properties:
        name:
          example: "UniqueClientName"
          type: "string"
          description: "New Client Name"
        archived:
          example: "false"
          type: "string"
          description: "Archived status (false = active)"
    FarmResponse:
      required:
        - "farmId"
        - "farmName"
        - "orgId"
        - "clientId"
      properties:
        farmId:
          type: "string"
        farmName:
          type: "string"
        clientId:
          type: "string"
        clientName:
          type: "string"
        clientUri:
          type: "string"
        orgId:
          type: "integer"
          format: "int64"
        archived:
          type: "boolean"
        sourceModifiedDate:
          type: "string"
        sourceCreatedDate:
          type: "string"
        createdContributionId:
          type: "string"
          description: "Id of the system which created the farm"
        modifiedContributionId:
          type: "string"
          description: "Id of the system which last modified the farm like AppId"
        createdSourceNode:
          type: "string"
          description: "The node which created the farm"
        modifiedSourceNode:
          type: "string"
          description: "The node which last modified the Farm"
        createdBy:
          type: "string"
          description: "The Id of the entity which created the farm"
        modifiedBy:
          type: "string"
          description: "The Id of the entity which last modified the farm"
    Errors:
      type: "object"
      format: "Errors/DataValidationException"
      properties:
        errors:
          type: "array"
          items:
            type: "object"
            format: "Error/ConstraintViolation"
            example:
              guid: "438d14c1-db6f-402a-a349-942ccab36c59"
              message: "invalid client name"
              code: 400
              field: "client name"
              invalidValue: "?????"
          properties:
            guid:
              type: "string"
              format: "uuid"
              example: "438d14c1-db6f-402a-a349-942ccab36c59"
            message:
              type: "string"
              description: "A description of the error translated into the language specified in the 'Accept-Language' header if available, otherwise English"
              example: "invalid client name"
            code:
              type: "string"
              description: "A string constant representing the type of error"
              example: 400
            field:
              type: "string"
              description: "The name of the property or parameter deemed invalid"
              example: "client name"
            invalidValue:
              type: "string"
              description: "The value that was supplied for this field in the request"
              example: "?????"
    MalformedRequestError:
      type: "object"
      properties:
        "@type":
          type: "string"
          example: "Errors"
        errors:
          type: "array"
          items:
            properties:
              "@type":
                type: "string"
                example: "Error"
              guid:
                type: "string"
                format: "uuid"
                example: "ed292512-1f3c-4285-83c3-1fb084423f9b"
              message:
                type: "string"
                example: "This field is required."
        otherAttributes:
          type: "object"
          example: {}
